print("Aloha\nWinnie")
print("Mele Kalikimaka\"Hauʻoli makahiki hou")
phrase = "Aloha Winnie"
print(phrase)
print(phrase + " Mahalo~")
print(phrase.lower())
print(phrase.upper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase[6])
print(phrase.index("h"))
print(phrase.replace("Aloha", "Mahalo"))